theme: minima
title: learning
author:
  # Biographic information
  ---
  avatar: profile.png
  name: John Trendler
  
  avatar           : "profile.png"
  name             : "John Trendler"
  pronouns         : "he/him"  
  bio              : "just dabbling"
  location         : "Claremont, CA"
---



